### PR TITLE
Feature/48 update vc docs

### LINKED ISSUE #48: Update verifiable credentials documentation
Update the verifiable credentials documentation to explain the latest technical capabilities provided by https://github.com/verida/verida-js/pull/157

### PR DESCRIPTION
**Pull request by tahpot**
Closes #48 

@nick-verida I have made the following changes for you to review:

- Updated navigation
- Replaced the previous verifiable credentials documentation with detailed notes on how the library works and how to use it
- Added lots of @todo messages

The @todo sections still need to be filled in (or hidden for now). I am assuming you or someone else in the team can fill those in from here to complete this PR?

### CODE REVIEW

**Comment by nick-verida** [comment]
@tahpot one thing that the old docs had that we found extremely useful when trying to build things on the old version of the library was screenshots that showed which part of the VC experience in the Vault correspond to which fields in the code. For example:

image

and

image

This was actually very unintuitive, because there are `name` and `summary` fields in the schema and the `message` parameter (which is actually used as a subject-type field in the notification), and this was the only place it is documented how the Vault handles them.

Do you know if this behaviour remains the same?

**Comment by nick-verida** [comment]
Also how does a developer get their icon to show up as the signer?

**Comment by tahpot** [comment]
>@tahpot one thing that the old docs had that we found extremely useful when trying to build things on the old version of the library was screenshots that showed which part of the VC experience in the Vault correspond to which fields in the code.

I see what you mean.

Those points relate to the Vault messaging system rather than specifically to sending a credential.

What if we do the following?

1. Update the `concepts/messaging` section to explain how accounts can get their icon to appear (for all inbox messages, not just credentials)
2. Create a "Credentials tutorial" that has screenshots and walks through creating and sending a credential to a user's vault. This can also be published on medium
3. If we do (2). We adjust the navigation to have a `Tutorials` section. Move the current `Tutorial` to be `Interactive Tutorial` and can then add more tutorials in the future.

>Also how does a developer get their icon to show up as the signer?

I'll add some notes on this.

**Comment by nick-verida** [comment]
> Update the concepts/messaging section to explain how accounts can get their icon to appear (for all inbox messages, not just credentials)

Agree

> Create a "Credentials tutorial" that has screenshots and walks through creating and sending a credential to a user's vault. This can also be published on medium
If we do (2). We adjust the navigation to have a Tutorials section. Move the current Tutorial to be Interactive Tutorial and can then add more tutorials in the future.

Why not just do the tutorial as an interactive one? It's maybe 10% more work (just need to wrap the JS code in JSX), I was intending to do that anyway (see #28 ) and we can basically copy and paste the back to Medium as an article anyway.

**Comment by tahpot** [comment]
>Why not just do the tutorial as an interactive one?

Good idea. I see you have this issue which I assume is for that task: https://github.com/verida/documentation/issues/28

I'll complete the other items within this issue / PR.

**Comment by tahpot** [comment]
@nick-verida I have now completed the additional items as discussed above. Please review and lmk if anything needs further refining.

I am handing this feature branch and PR over to you for co-ordinating adding the missing `@todo` items in the [verifiable credentials page](https://github.com/verida/documentation/blob/174ed20232a83cd960d854b500474033b82af3f8/docs/extensions/verifiable-credentials.md)

**Comment by nick-verida** [comment]
Issue:

1. Go to front page, search for a DID
2. Link goes to the old (non `/did`) URL

**Pull request merged**
